### ISSUE TITLE
Marshal/Unmarshal with slices doesn't appear to work in some cases.

### ISSUE THREAD

**Issue by yonderblue** [distributedio/configo#3]
Or maybe more accurately, unless there is an initialized member in the slice. But when there is not I think it isn't supposed to print out the field tag?

Related would be specifying a default for a slice of structs, is that possible?

**Comment by yonderblue** [comment]
here is one example of how the slice's aren't working.

```
package main

import (
    "fmt"

    "github.com/shafreeck/configo"
)

type Item struct {
    Val   string `cfg:" ; thedefault; ; A desc."`
    Other int    `cfg:" ; 5; ; `
}

type Config struct {
    AField bool `cfg:" ; false; ; A field desc."`
    Items  []Item
}

func main() {
    c := Config{Items: []Item{}}
    toml := `
[[items]]
val = "booga!"
[[items]]
other = 1
[[items]]
val = "party!"`
    if err := configo.Unmarshal([]byte(toml), &c); err != nil {
        panic(err)
    }
    fmt.Printf("%+v", c)
}
```

prints

```
{AField:false Items:[{Val:booga! Other:0} {Val: Other:1} {Val:party! Other:0}]}
```

Is that right? Val and Other both have a default yet it is no where in the output.

**Comment by shafreeck** [comment]
It maybe a bug. Thanks for your feedback. I would like to test it later.

**Comment by shafreeck** [comment]
@gaillard The bug has been fixed, you can have a try. BTW, you miss a double quote on this line of your testing code

```
Other int    `cfg:" ; 5; ; `
```
